### PR TITLE
Support asymmetric sanitization to compensate for node-expat's problems

### PR DESCRIPTION
**Pull request by ehoogerbeets**

### CODE REVIEW

**Comment by c4milo** [comment]
@ehoogerbeets LGTM, would the current tests covered properly your changes or should we add more?

**Comment by ehoogerbeets** [comment]
Good point... we probably do need more tests. Let me work on that.

**Comment by ehoogerbeets** [comment]
@c4milo The tests have been updated with the special chars that should not be escaped on a round-trip.

**Comment by c4milo** [comment]
Nice! thanks @ehoogerbeets!

**Pull request merged**
