### PR TITLE
Updated Joi version from v9.0.4 to v10.0.0

### PR DESCRIPTION
**Pull request by sidag95**
- Updated Joi from v9.0.4 to v.13.1.0
- Joi@v9.0.4 uses an old version of moment which has a security vulnerability
- Joi@v10.0.0 doesn't use moment anymore

Issue for this PR: https://github.com/buglabs/node-xml2json/issues/152

### CODE REVIEW

**Comment by will-stone** [comment]
xml2json is great. Thanks for this project. However please accept this merge request as the version of Moment that your current version of Joi uses, has a security flaw.

**Comment by c4milo** [comment]
thanks for the contribution @will-stone!

**Comment by will-stone** [comment]
Wow, I wasn't expecting an immediate response. Thank-you.

**Comment by c4milo** [comment]
@will-stone it was a straightforward change ;D

**Pull request merged**
