### PR TITLE
Upgrade node-expat to ensure compatibility with node 10

### PR DESCRIPTION
**Pull request by Clement134**
Versions of node-expat oldest than 2.3.17 are not compatible with node 10: https://github.com/astro/node-expat/pull/190

@c4milo is it possible to merge this pull request and create a new release with all the pending fixes since the latest version ?

### CODE REVIEW

**Comment by c4milo** [comment]
I will cut a new release tomorrow. Thanks!

**Comment by 3z3qu13l** [comment]
@c4milo Would be great to have 0.11.3 ;)

**Comment by maximnara** [comment]
Hey! Would it be new version with upgraded node support soon?

**Comment by c4milo** [comment]
I will merge this PR once Travis passes. It looks like we have some memory leaks, most likely in dependencies.

**Comment by Clement134** [comment]
@c4milo by memory leaks you refer to this error message: "The following leaks were detected:SharedArrayBuffer, Atomics, WebAssembly" ?

Those are not real memory leaks, but false positive due to differences between nodejs version used for tests, and the nodejs version handled by the version of lab. I think the purpose of #159 is precisely to fix that.

**Comment by c4milo** [comment]
Why does it keep showing up in #159 Travis ouptput if it is fixing it?

**Comment by Clement134** [comment]
#159 fixes lab false positive on node 8 and 9. But we have to upgrade to at least lab@15.5.0 in order to fix the fix the remaining error message (https://github.com/hapijs/lab/pull/837).

**Comment by 3z3qu13l** [comment]
Hello @c4milo ,
Can merge this PR since the memory leaks is in a dev dependency and not in the code itself ?

**Comment by Clement134** [comment]
> I will merge this PR and #159 once Travis passes. It looks like we have some memory leaks, most likely in dependencies.

I have upgraded lab to the latest version, now all the tests on Travis are green.
@c4milo could you merge this PR ?

**Comment by c4milo** [comment]
Done. Thanks @Clement134!

**Pull request merged**
