### PR TITLE
add sanitize options for toXml function. (& -> &amp;, etc.)

### PR DESCRIPTION
**Pull request by miira**
I needed to put '&' into the XML file in the entity form (&amp;). The same sanitize function as in toJson function is used to achieve the result.

Second reason:
The options for toXml function were not used (resulted in [Object object] at the beginning of XML file, if you tried to use them), fixed README.

### CODE REVIEW

**Comment by RickyJiao** [comment]
I also need this feature. I just created a issue before I noted this PR...

**Comment by brutalhonesty** [comment]
:+1: Do want this merged please!

**Comment by c4milo** [comment]
@brutalhonesty I will review again today, fix conflicts and merge.

**Comment by brutalhonesty** [comment]
@c4milo Thanks for the quick response! :)

**Comment by c4milo** [comment]
@brutalhonesty done. I will publish a new version to npm soon.

**Pull request closed without merging**
