### PR TITLE
coerce may be boolean or object

### PR DESCRIPTION
**Pull request by danielb2**
Fixes https://github.com/buglabs/node-xml2json/issues/89

### CODE REVIEW

**Comment by c4milo** [comment]
@danielb2 can we add a simple test to make sure it doesn't happen again?

**Comment by danielb2** [comment]
There is one. Unfortunately the tests are in a bit of a bad state.   In fact, I noticed several are broken. When I redid the tests, I only focused on the tests in test/index.js but the others also need to be redone.

**Comment by danielb2** [comment]
FYI, the test https://github.com/buglabs/node-xml2json/blob/master/test/test-coerce.js  failed before this fix.

**Comment by c4milo** [comment]
@danielb2 weird, I remember I fixed those test.

**Comment by danielb2** [comment]
I was thinking to put them into the test/index.js using only lab for the tests now. But I wanted to get this fix in for @FGTgb quickly

**Pull request merged**
