### PR TITLE
change to use lab. validate input options

### PR DESCRIPTION
**Pull request by danielb2**
I'm planning to add at least one new feature, and I'm starting with improving the test suite since it makes things easier for me.

I hope you find this useful

### CODE REVIEW

**Comment by c4milo** [comment]
@danielb2 Hey! thanks for your PR and apologies the late review. Your changes look good to me despite the addition of several third-party dependencies. I'm generally in favor of not adding third-party dependencies for small libraries like xml2json, especially if the value added by those is not proportional to the additional code being installed. But, I will make an exception as most of the dependencies are devDependencies.

Thanks again!

**Comment by danielb2** [comment]
:+1:

**Comment by c4milo** [comment]
@danielb2 there is one issue I'm seeing, though. When there is no options being passed, the defaults are not being set and

**Comment by danielb2** [comment]
ok, I'll have a look now

**Comment by danielb2** [comment]
https://github.com/buglabs/node-xml2json/pull/88

**Comment by danielb2** [comment]
we should add a test for that condition to make sure it parses as expected with no options. I didn't realize there was no test for that already

**Comment by c4milo** [comment]
@danielb2 agreed, to avoid regressions.

**Pull request merged**
